#!/bin/bash

function check_help {
  # taken from shocco
  if expr -- "$*" : ".*--help" >/dev/null; then
    grep '^#/' <"$shome/bin/$(basename -- "$0")" | cut -c4-
    exit 0
  fi
}

function require {
  local library="$1"; shift
  source "$shome/lib/_$library" "$@"
}

function parse_command_line {
  FLAGS "$@" || return 1
  eval set -- "${FLAGS_ARGV}"
}

function _main {
  if [[ "$0" = "-bash" ]]; then
    echo 'ERROR: cannot source library without setting $shome'
    exit 1
  fi

  if [[ -z "$shome" ]]; then
    shome="$(cd -P -- "$(dirname -- "$0")/.." && pwd -P)"
  fi

  require "shflags"

  PATH="$shome/bin:$PATH"
}

_main "$@"
