#!/bin/bash

if [[ "$0" = "-bash" ]]; then
  echo 'ERROR: cannot source library without setting $shome'
  exit 1
fi

if [[ -z "$shome" ]]; then
  shome="$(cd -P -- "$(dirname -- "$0")/.." && pwd -P)"
fi
  
function check_help {
  # taken from shocco
  if expr -- "$*" : ".*--help" >/dev/null; then
    grep '^#/' <"$shome/bin/$(basename -- "$0")" | cut -c4-
    exit 0
  fi
}
