#!/bin/bash

if [[ "$0" = "-bash" ]]; then
  echo 'ERROR: cannot source library without setting $shome'
  exit 1
fi

if [[ -z "$shome" ]]; then
  shome="$(cd -P -- "$(dirname -- "$0")/.." && pwd -P)"
fi
  
function dump_args {
  echo "0' $shome"

  local i=1
  while [[ "$#" > 0 ]]; do
    echo "$i: $1"; shift
    i=$((i+1))
  done
}

function check_help {
  if expr -- "$*" : ".*--help" >/dev/null; then
    grep '^#/' <"$shome/bin/$(basename -- "$0")" | cut -c4-
    exit 0
  fi
}
