#!/bin/bash

function aws_profile {
  case "${AWS_DEFAULT_PROFILE:-default}" in
    default)
      echo ""
      ;;
    *)
      echo "$AWS_DEFAULT_PROFILE${AWS_DEFAULT_REGION:+/}"
      ;;
  esac
}

function aws_region {
  if [[ -n "${AWS_DEFAULT_REGION:-}" ]]; then
    echo "${AWS_DEFAULT_REGION}: "
  fi
}

function prompt_aws {
  # aws profile + region
  echo "$(aws_profile)$(aws_region)"
}
