#!/bin/bash

if [[ "$#" > 0 ]]; then
  CUE="$1"; shift
else
  CUE="$(cd -P -- "$(dirname -- "${BASH_SOURCE}")/.." && pwd -P)"
fi  

source "$CUE/libexec/_nim"
source "$CUE/libexec/_bindings"
source "$CUE/libexec/_solarized"
source "$CUE/libexec/_prompt"

: ${PS1_START:='--'}
: ${PS1_LEFT:='${prn_pwd}'}
: ${PS1_RIGHT:='${prn_ssh}'}
: ${PS1_END:='${scomment}--'}
: ${PS1_BREAK:='${PS1_START}'}
