#!/bin/bash

function prompt_shell {
  if [[ "${SHLVL}" = "${SHLVL_INITIAL}" ]]; then
    echo "${shigh}\$HISTCMD "
  else
    if [[ -n "${SHLVL_NAME:-}" ]]; then
      echo "${scyan}$SHLVL_NAME${scomment}/${shigh}\$HISTCMD "
    else
      echo "${scyan}$(( SHLVL - SHLVL_INITIAL ))${scomment}/${shigh}\$HISTCMD "
    fi
  fi
}

function prompt_error {
  # optional error
  local err_last="$RETVAL"
  if [[ -n $err_last && $err_last != 0 ]]; then
    echo -n "${sorange}[${sred}$err_last${sorange}]${scomment}:"
  fi
}

function prompt_jobs {
  # optional background jobs
  local bg_jobs="$(jobs -l | wc -l)"
  if [[ $bg_jobs > 0 ]]; then
    echo -n "${sorange}[${syellow}$bg_jobs${sorange}]${scomment}:"
  fi
}

function prompt_root {
  if [[ $UID = 0 ]]; then
    echo -n "${sorange}>>> "
  else
    echo -n "${shigh}=> "
  fi
}

function prompt_cli {
  echo -n "${shigh}"
}

function prompt_filler {
  local prn_prompt="$1"; shift

  if [[ -z ${COLUMNS:-} ]]; then
    COLUMNS="$(tput cols)"
  fi

  if [[ -n ${COLUMNS:-} ]]; then
    local len_prompt=$(echo -n "$prn_prompt" | perl -pe 's{\\\[\\e\[\d+;\d+m\\\]}{}g' | wc -c | tr -d " ")
    local txt_fill=" "
    for _ in $(eval echo {1..$((COLUMNS - len_prompt - 1))}); do
      txt_fill="${txt_fill}-"
    done
    echo "${scomment}${txt_fill}"
  fi
}

function eval_prompts {
  local p
  for p in "$@"; do
    local fn_prn="prompt_${p}"
    local nm_prn="prn_${p}"
    eval "$nm_prn=\$($fn_prn)"
  done
}

function prompt {
  local RETVAL="$?"

  eval_prompts jobs root

  if [[ -n "${DISPLAY:-}" ]]; then
    if [[ $UID = 0 ]]; then
      #slight light
      true
    else
      #sdark dark
      true
    fi
  fi

  eval_prompts error shell cli

  if [[ -z ${COLUMNS:-} ]]; then
    eval_prompts $(echo "${PS1_LEFT}" | perl -ne 'map { print "$_\n" } m{\$\{prn_(\w+)\}}g' | sort -u)
    local prn_filler=""
  else
    eval_prompts $(echo "${PS1_LEFT}${PS1_RIGHT}" | perl -ne 'map { print "$_\n" } m{\$\{prn_(\w+)\}}g' | sort -u)
    local prn_filler="$(prompt_filler "$(eval echo "${PS1_START}${PS1_LEFT}${PS1_RIGHT}${PS1_END}")")"
  fi

  "$@"
}

if [[ "$#" = 0 ]]; then
  set -- default_theme
fi

PROMPT_COMMAND="prompt $@"

# vim: ts=2 sw=2 et
