#!/bin/bash

if [[ "$#" > 0 ]]; then
  CUE="$1"; shift
else
  CUE="$(cd -P -- "$(dirname -- "${BASH_SOURCE}")/.." && pwd -P)"
fi  

source "$CUE/libexec/_nim"
source "$CUE/libexec/_bindings"
source "$CUE/libexec/_solarized"

if [[ "$#" = 0 ]]; then
  set -- default
fi

__nm_theme="$1"; shift

source "$CUE/libexec/_theme_${__nm_theme}"
source "$CUE/libexec/_prompt" ${__nm_theme}_theme
