#!/bin/bash

if [[ "$#" > 0 ]]; then
  CUE="$1"; shift
else
  CUE="$(cd -P -- "$(dirname -- "${BASH_SOURCE}")/.." && pwd -P)"
fi  

source "$CUE/libexec/_nim"
source "$CUE/libexec/_bindings"
source "$CUE/libexec/_solarized"

source "$CUE/libexec/_theme_default"
source "$CUE/libexec/_prompt" default_theme
