#!/bin/bash

function prompt_ssh {
  # ssh trail
  local hst_this
  if [[ -f $HOME/.name ]]; then
    hst_this=$(cat $HOME/.name)
  else
    hst_this=$(hostname | awk -F.  'BEGIN { OFS="."; } {$(NF-1)=""; $NF=""; print $0; }' | sed 's#[.]*$##')
  fi

  if [[ -z $hst_this ]]; then
    hst_this=$(hostname -s)
  fi

  local txt_origin
  if [[ -n ${LC_ORIGIN:-} && -z $LC_FROM ]]; then
    txt_origin="/$LC_ORIGIN"
    export LC_ORIGIN="$hst_this${txt_origin}"
  fi

  if [[ -n ${LC_ORIGIN:-} && $LC_ORIGIN != "$hst_this" ]]; then
    echo " ${shigh}$LOGNAME@$hst_this${scomment}${txt_origin}"
  else
    echo " ${shigh}$LOGNAME@$hst_this"
  fi
}
