#!/bin/bash

#/ NAME
#/     jason-bourne-again  -- uses the jason bourne lib
#/
#/ SYNOPSIS
#/     jason bourne again

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/bin/_treadstone"

# parse the command-line
DEFINE_string 'sequel' "again" 'Name of sequel' 's'

# entry point
function main {
  echo "He stars in $FLAGS_sequel"
}

require 'sub' "$BASH_SOURCE" "$@"
