#!/bin/bash

#/ NAME
#/     jason -- uses the jason bourne lib
#/
#/ SYNOPSIS
#/     jason

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/bin/_treadstone"

# parse the command-line
DEFINE_boolean 'nancy' "$FLAGS_FALSE" 'What is her name?' 'n'

# entry point
function main {
  echo "$FLAGS_nancy"
}

parse_command_line "$@" || exit $?
eval set -- "${FLAGS_ARGV}"

# pass arguments to entry point
main "$@"
