#!/bin/bash

#/ NAME
#/     jason-bourne  -- uses the jason bourne lib
#/
#/ SYNOPSIS
#/     jason bourne

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/bin/_treadstone"

# parse the command-line
DEFINE_string 'weapon' "fists" 'weapon of choice' 'w'

# entry point
function main {
  echo "$FLAGS_weapon"
}

parse_command_line "$@" || exit $?
eval set -- "${FLAGS_ARGV}"

# pass arguments to entry point
main "$@"
