#!/bin/bash

#/ NAME
#/     jason-bourne  -- uses the jason bourne lib
#/
#/ SYNOPSIS
#/     jason bourne

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/bin/_treadstone"

# parse the command-line
DEFINE_string 'weapons' "fists" 'supremacy' 's'

# entry point
function main {
  echo "He fights with $FLAGS_weapons"
}

require 'sub' "$BASH_SOURCE" "$@"
