#!/bin/bash

#/ NAME
#/     jason -- uses the jason bourne lib
#/
#/ SYNOPSIS
#/     jason

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/bin/_treadstone"

# parse the command-line
DEFINE_string 'name' "Nancy" 'What is her name?' 'n'

# entry point
function main {
  echo "His girlfriend is $FLAGS_name"
}

require 'sub' "$BASH_SOURCE" "$@"
