#!/bin/bash

#/ NAME
#/     shocco -- wrapper to call shocco under virtualenv
#/
#/ SYNOPSIS
#/     shocco ...

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$0")/.." && pwd -P)"

# load a meat library
source "$shome/bin/_prime" "$@"

# entry point
function main {
  export BUNDLE_GEMFILE="$shome/.doc/Gemfile"
  export shome

  ( cd $shome/.doc && bundle check 2>&1 >/dev/null || { bundle install --quiet --local --path vendor/bundle || bundle check > /dev/null; } )
  exec bundle exec $shome/bin/venv "$shome/libexec/shocco.sh" "$@"
}

# define command line options:
#   var name, default, description, short option

# parse the command-line
#parse_command_line "$@" || exit $?
#eval set -- "${FLAGS_ARGV}"

# pass arguments to entry point
main "$@"
